services:
  - type: web
    name: vidlink-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vidlink-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false

databases:
  - name: vidlink-db
    databaseName: vidlink
    user: vidlink
